name: Django_Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry install --no-root

    - name: Run Tests with environment variables
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        BACKEND_URL: ${{ secrets.BACKEND_URL }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
        poetry run python manage.py test
        
    - name: Update code & Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: "${{ secrets.MAKEBFFS }}"
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          echo "${{secrets.MAKEBFFS}}" >> $HOME/makebffs.pem
          chmod 600 $HOME/makebffs.pem
          ssh -i $HOME/makebffs.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_IP }}
          cd /home/ubuntu/backend/django/
          git pull origin main
          cd /home/ubuntu/
          sudo docker compose up --build -d
          sudo docker compose restart
